//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languaje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languaje() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Languaje", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Contáctanos!.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convirtiendo....
        /// </summary>
        internal static string converting {
            get {
                return ResourceManager.GetString("converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargando....
        /// </summary>
        internal static string downloading {
            get {
                return ResourceManager.GetString("downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, no fue posible subir archivo. Error encontrado:.
        /// </summary>
        internal static string errorEncountered {
            get {
                return ResourceManager.GetString("errorEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al procesar documento: consulte a su administrador.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Conversión.
        /// </summary>
        internal static string newConversion {
            get {
                return ResourceManager.GetString("newConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se cumplen los requerimientos.
        /// </summary>
        internal static string noRequirements {
            get {
                return ResourceManager.GetString("noRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible realizar la conversión.
        /// </summary>
        internal static string notConvert {
            get {
                return ResourceManager.GetString("notConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en formato de documento Word: No se encuentra Sección de la Revista.
        /// </summary>
        internal static string NotFoundSection {
            get {
                return ResourceManager.GetString("NotFoundSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en formato de documento Word: No se encuentra Titulo principal del artículo.
        /// </summary>
        internal static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título de la Revista.
        /// </summary>
        internal static string r1 {
            get {
                return ResourceManager.GetString("r1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abreviatura de la Revista.
        /// </summary>
        internal static string r2 {
            get {
                return ResourceManager.GetString("r2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ISSN impreso.
        /// </summary>
        internal static string r3 {
            get {
                return ResourceManager.GetString("r3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editorial/Institución.
        /// </summary>
        internal static string r4 {
            get {
                return ResourceManager.GetString("r4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número, Volumen y año de cada artículo a convertir.
        /// </summary>
        internal static string r5 {
            get {
                return ResourceManager.GetString("r5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Páginas del artículo.
        /// </summary>
        internal static string r6 {
            get {
                return ResourceManager.GetString("r6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de publicación del artículo.
        /// </summary>
        internal static string r7 {
            get {
                return ResourceManager.GetString("r7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona el archivo:.
        /// </summary>
        internal static string seletFile {
            get {
                return ResourceManager.GetString("seletFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar conversión.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar conversión del archivo:.
        /// </summary>
        internal static string startFileConversion {
            get {
                return ResourceManager.GetString("startFileConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en webService, no se puede comprimir el archivo, intentelo más tarde.
        /// </summary>
        internal static string tryLater {
            get {
                return ResourceManager.GetString("tryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir Archivo.
        /// </summary>
        internal static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo cargado correctamente.
        /// </summary>
        internal static string uploadedCorrectly {
            get {
                return ResourceManager.GetString("uploadedCorrectly", resourceCulture);
            }
        }
    }
}
